### ISSUE TITLE
No entitys shows up

### ISSUE THREAD

**Issue by benzon** [pedr0fontoura/gtav-audio-occlusion#25]
Hey,

So trying to learn this tool, but in the Portals Entites nothings shows up with any of the MLO's i have tested so fare, what might be the problem here?

**Comment by mickeygeecom** [comment]
If directly opening a FiveM resource folder in CodeWalker, will result in the exported .xml files will be having hashed names.
This is no go, as you'd need to ensure archetypeName is a string - and *all* lowercase.

So instead of 8593599_HASH (afair) - it should be something like 'prettycoolmlo_col' as ytyp name f.eg.
So, you'd need to put your interior inside GTA, then open the stuff in CodeWalker, then you will get correct/translated names - and not hashed values/names.

**Comment by benzon** [comment]
Okay that kinda makes sence @mickeygeecom and it's the same your would to with the escrowed mlo's to get the correct output of names?

**Comment by mickeygeecom** [comment]
Yup, same procedure ( ... as last year James) 😄

**Comment by benzon** [comment]
Well ill create a mod folder then for it haha, gonna be borring but ye gotta be done

**Comment by pedr0fontoura** [comment]
You need to make sure that the relevant entities are **attached** to the portal. I'll be closing this issue since I already talked with @benzon.
