### ISSUE TITLE
Program ignores portals without entities

### ISSUE THREAD

**Issue by e-49** [pedr0fontoura/gtav-audio-occlusion#4]
Hello, i don't know bug it or not, but this program ignores portals without attached entities( for example i'm load ymap and ytyp of vanilla tunnel interior, and i'm got empty file:

```<?xml version="1.0" encoding="UTF-8"?>
<naOcclusionInteriorMetadata>
  <PortalInfoList itemType="naOcclusionPortalInfoMetadata"/>
  <PathNodeList itemType="hash_771E3577"/>
</naOcclusionInteriorMetadata>
```
If someone too have same issue, i am guess it can be fixes by attach any props to all portals in interior

**Comment by pedr0fontoura** [comment]
Can you provide the files you used so I can look into this?

**Comment by e-49** [comment]
[test_tunnel.zip](https://github.com/pedr0fontoura/gtav-audio-occlusion/files/6993559/test_tunnel.zip)

**Comment by pedr0fontoura** [comment]
It's not because of attached entities but because of the portal's flags. The flag is set to 66 which makes the portal be filtered [here](https://github.com/pedr0fontoura/gtav-audio-occlusion/blob/50a6993c54c136d15a74eff477e3551566d33ff2/src/core/classes/audioOcclusion/index.ts#L113)

You can just comment that line to make it work.

I'm not really sure about how to proceed here, this filter seems to be quite accurate in removing unwanted portals like mirrors, etc. I'll probably need to look more into portal flags before making any changes.
